from manim import *

class PSeries(Scene):
    def construct(self):

        title = Tex("P-Series Test")
        test = MathTex(r"\text{If } k > 0 \text{ then } \sum_{ { n=k } }^{ { \infty } } \frac{1}{ { n^{p} } } \text{ converges if } p > 1 \text{ and diverges if } p \leq 1")
        simplifiedTest = MathTex(r"\text{If } p > 1 \text{ then it converges, if } p \leq 1 \text{ then it diverges}")
        example1 = MathTex(r"\sum_{ { n=4 } }^{ { \infty } } \frac{1}{ { n^{7} } }")
        example1Simp = MathTex(r"7 > 1 \text{ so the series converges}")
        example2 = MathTex(r"\sum_{ n=1 }^{ \infty }\frac{1}{ \sqrt{n}}")
        example2Simp = MathTex(r"\frac{1}{2} \leq 1 \text{ so the series diverges}")

        self.play(Write(title))
        self.wait(2)
        self.play(title.animate.to_edge(UP, buff=0.5))
        self.play(Write(test))
        self.wait(2)
        self.play(ReplacementTransform(test, simplifiedTest))
        self.wait(2)
        self.play(simplifiedTest.animate.to_edge(DOWN, buff=0.5))
        self.wait(2)
        self.play(Write(example1))
        self.wait(2)
        self.play(example1.animate.shift(UP*2))
        self.wait(2)
        self.play(Write(example1Simp))
        self.wait(2)
        self.play(FadeOut(example1), FadeOut(example1Simp))
        self.wait(2)
        self.play(Write(example2))
        self.wait(2)
        self.play(example2.animate.shift(UP*2))
        self.wait(2)
        self.play(Write(example2Simp))
        self.wait(2)
        self.play(FadeOut(example2), FadeOut(example2Simp), FadeOut(simplifiedTest), FadeOut(title))
        self.wait(2)