from manim import *

class DivergenceTest(Scene):
    def construct(self):
        
        title = Tex("The Divergence Test")
        test = MathTex(r"\text{If} \lim_{n\to\infty} a_{n} \neq 0 \text{ then} \sum a_{n} \text{will diverge}")
        example1 = MathTex(r"\sum_{n=1}^{\infty}{1}{n}")
        example1Limit = MathTex(r"\lim_{n\to\infty}\sum_{n=1}^{\infty}\frac{1}{n}")
        example1Answer = MathTex(r"")
        example2 = MathTex(r"\sum_{n=1}^{\infty}{1}{n^{2}}")
        example2Limit = MathTex(r"\lim_{n\to\infty}\sum_{n=1}^{\infty}\frac{1}{n^{2}}")
        example2Answer = MathTex(r"")
        example3 = MathTex(r"\sum_{n = 0}^{\infty}\frac{4n^{2}-n^{3}}{10 + 2n^{3}}")
        example3Limit = MathTex(r"\lim_{n\to\infty}\sum_{n = 0}^{\infty}\frac{4n^{2}-n^{3}}{10 + 2n^{3}}")
        example3LimitSimplified = MathTex(r"\lim_{n\to\infty}\sum_{n = 0}^{\infty}\frac{-n^{3}}{2n^{3}}")
        example3Answer = MathTex(r"= -\frac{1}{2}").shift(DOWN*1.5)
        example3Final = MathTex(r"\sum_{n = 0}^{\infty}\frac{4n^{2}-n^{3}}{10 + 2n^{3}}")
        example3cord = MathTex(r" \text{Diverges}").shift(DOWN*1.5)

        self.play(Write(title))
        self.wait(2)
        self.play(ReplacementTransform(title, test))
        self.wait(2)
        self.play(test.animate.to_edge(UP,buff=0.5))
        self.wait(2)
        self.play(Write(example3))
        self.wait(2)
        self.play(ReplacementTransform(example3, example3Limit))
        self.wait(2)
        self.play(example3Limit.animate.shift(UP*1.5))
        self.wait(2)
        self.play(Write(example3LimitSimplified))
        self.wait(2)
        self.play(Write(example3Answer))
        self.wait(2)
