from manim import *
#TO DO WRITE THE SEQUENCES INTRODUCTION
class definitionOfSeries(Scene):
    def construct(self):
        classTitle = Tex("Calculus 2/BC").to_edge(UP, buff=1)
        title = Tex("Series")

        exSeq = MathTex(r"\left\{ a_n \right\}_{n=1}^{\infty}")
        exSeqExpand = MathTex(r"\left\{ a_n \right\}_{n=1}^{\infty} = a_1, a_2, a_3, a_4, \cdots, a_n")
        s_1 = MathTex(r"s_1 = a_1")
        s_2 = MathTex(r"s_2 = a_1 + a_2")
        s_3 = MathTex(r"s_3 = a_1 + a_2 + a_3").to_edge(UP,buff=4)
        s_4 = MathTex(r"s_4 = a_1 + a_2 + a_3 + a_4").to_edge(UP,buff=5)
        partialSum = MathTex(r"s_n = a_1 + a_2 + a_3 + a_4 + \cdots + a_n")
        partialSumEqualsSeries = MathTex(r"s_n = a_1 + a_2 + a_3 + a_4 + \cdots + a_n = \sum_{i=1}^{n}a_i") 
        limitToInfOfPartialSum = MathTex(r"\lim_{x\to\infty} s_n")
        limitToInfOFSeries = MathTex(r" = \lim_{x\to\infty} \sum_{i=1}^{n}a_i").next_to(limitToInfOfPartialSum,RIGHT*0.5)
        infiniteSeriesNotation = MathTex(r" = \sum_{i=1}^{\infty}a_i").next_to(limitToInfOFSeries, RIGHT*0.5)

        self.wait(2)
        self.play(Write(classTitle))
        self.play(Write(title))
        self.wait(2)
        self.play(FadeOut(Group(title, classTitle)))
        self.wait(2)
        self.play(Write(exSeq))
        self.wait(2)
        self.play(ReplacementTransform(exSeq, exSeqExpand))
        self.wait(2)
        self.play(exSeqExpand.animate.to_edge(UP, buff=1))
        self.wait(2)
        self.play(Write(s_1))
        self.wait(2)
        self.play(s_1.animate.to_edge(UP, buff=2))
        self.wait(2)
        self.play(Write(s_2))
        self.wait(2)
        self.play(s_2.animate.to_edge(UP, buff=3))
        self.wait(2)
        self.play(Write(s_3))
        self.wait(2)
        self.play(Write(s_4))
        self.wait(2)
        self.play(ReplacementTransform(Group(s_1, s_2, s_3, s_4), partialSum), exSeqExpand.animate.move_to(ORIGIN).shift(UP))
        self.wait(2)
        self.play(ReplacementTransform(Group(partialSum, exSeqExpand), partialSumEqualsSeries))
        self.wait(2)
        self.play(partialSumEqualsSeries.animate.to_edge(UP,buff=1), Write(limitToInfOfPartialSum))
        self.wait(2)
        self.play(Group(limitToInfOfPartialSum).animate.shift(LEFT))
        limitToInfOFSeries.next_to(limitToInfOfPartialSum,RIGHT*0.5)
        self.play(Write(limitToInfOFSeries))
        self.wait(2)
        self.play(Group(limitToInfOfPartialSum, limitToInfOFSeries).animate.shift(LEFT))
        infiniteSeriesNotation.next_to(limitToInfOFSeries, RIGHT*0.5)
        self.play(Write(infiniteSeriesNotation))
        self.wait(2)
        self.play(FadeOut(Group(partialSumEqualsSeries, limitToInfOfPartialSum, limitToInfOFSeries, infiniteSeriesNotation)))
        self.wait(2)

class seriesNotation(Scene):
    def construct(self):

        exampleSeries = MathTex(r"\sum_{i=1}^{\infty} = \frac{3}{i^2+1}")

        self.wait(2)
        self.play(Write(exampleSeries))
        self.wait(2)
        self.play(FadeOut(exampleSeries))

class seriesProperties(Scene):
    def construct(self):
        
        theorum1Text = MathTex(r"\text{1. }\sum_{}^{}ca_n \text{, where c is any number. is also convergent and}")
        theorum1 = MathTex(r"\sum_{}^{}ca_n = c\sum_{}^{}a_n")
        theorum2Text = MathTex(r"\text{2. }\sum_{n=k}^{\infty}a_n \pm \sum_{n=k}^{\infty}b_n \text{is also convergent and,}")
        theorum2 = MathTex(r"\sum_{n=k}^{\infty}a_n \pm \sum_{n=k}^{\infty}b_n = \sum_{n=k}^{\infty}(a_n \pm b_n)").next_to(theorum2Text,DOWN)
        multiSeriesInc = MathTex(r"(\sum_{n=k}^{\infty}a_n)(\sum_{n=k}^{\infty}b_n) \neq \sum_{n=k}^{\infty}a_nb_n")
        multiSeriesIncExp = MathTex(r"(a_1 + a_2 + a_3 + a_4 + \cdots + a_n)(b_1 + b_2 + b_3 + b_4 + \cdots + b_n)")
        quadEqAnalogy = MathTex(r"")

        self.wait(2)
        self.play(Write(theorum1Text))
        self.wait(2)
        self.play(theorum1Text.animate.shift(UP))
        self.play(Write(theorum1))
        self.wait(2)
        self.play(Group(theorum1Text, theorum1).animate.shift(UP*2))
        self.wait(2)

        self.play(Write(theorum2Text))
        self.wait(2)
        self.play(Write(theorum2))
        self.wait(2)